name: Build and test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build with no_std
      run: cargo build --no-default-features
    - name: Build default
      run: cargo build
    - name: Run tests with no_std
      run: cargo test --no-default-features
    - name: Run tests with no_std in release mode
      run: cargo test --no-default-features --release
    - name: Run tests default
      run: cargo test
    - name: Run tests default in release mode
      run: cargo test --release
